### ISSUE TITLE
Link to instance on the web?

### ISSUE THREAD

**Issue by cmdcolin** [SimHacker/CAM6#1]
Wasn't sure if there is an instance on the web, I set it up locally and it is very cool!

**Comment by SimHacker** [comment]
Thanks, I’m glad you got it to work and enjoy it! 

I rewrote it from scratch in JavaScript a while ago! 

It’s not quite “easy to use” or “well documented” yet, but you can have fun clicking around the control panel and tweaking all the buttons. 

There are lots of comments in the code! 

To get the controls, click on the mysterious gray rectangle in the upper left corner. 

http://www.donhopkins.com/home/CAM6 <http://www.donhopkins.com/home/CAM6>
https://github.com/SimHacker/CAM6 <https://github.com/SimHacker/CAM6>

-Don

**Comment by SimHacker** [comment]
Ah I thought you were referring to the old C++ code so I was telling you about the new(ish) JavaScript code — but that was what you were referring to! So I’ll refer you to the old C++ code (yuck) instead:

https://github.com/SimHacker/micropolis/tree/master/MicropolisCore/src/CellEngine <https://github.com/SimHacker/micropolis/tree/master/MicropolisCore/src/CellEngine>

That code is a much bigger pain in the ass to get running — which is why I rewrote it in JavaScript! 

And some older Forth and C code I wrote that eventually evolved into that C++ code:

http://www.donhopkins.com/home/code/cam.f.txt <http://www.donhopkins.com/home/code/cam.f.txt>
http://www.donhopkins.com/home/code/rules.f.txt <http://www.donhopkins.com/home/code/rules.f.txt>
http://www.donhopkins.com/home/code/cam.tgz <http://www.donhopkins.com/home/code/cam.tgz>

It’s based on Toffoli's and Margolis’s CAM6 hardware and FORTH rule definition software, which I have a copy of here:

http://www.donhopkins.com/home/code/tomt-cam-forth-scr.txt <http://www.donhopkins.com/home/code/tomt-cam-forth-scr.txt>
http://www.donhopkins.com/home/code/tomt-users-forth-scr.txt <http://www.donhopkins.com/home/code/tomt-users-forth-scr.txt>

Have fun! 

-Don

**Comment by cmdcolin** [comment]
I think when I had asked your domain was unavailable :) thanks for the extra info though!
